# Enable mouse emulation.
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_DEFAULT_MOVE_VAL=900
CONFIG_ZMK_POINTING_DEFAULT_SCROLL_VAL=10

# Change idle settings
# CONFIG_ZMK_IDLE_TIMEOUT=30000

# Deep sleep settings
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Custom keyboard name (max. 16 characters)
# CONFIG_ZMK_KEYBOARD_NAME="My Keyboard"
